# @package dataset.cingulate_left_CCD
dataset_name: cingulate_left_CCD
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/CCD/crops/2mm/CINGULATE./mask/Lskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/CCD/crops/2mm/CINGULATE./mask/Lskeleton_subject.csv
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/CCD/crops/2mm/CINGULATE./mask/Llabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/CCD/crops/2mm/CINGULATE./mask/Llabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/CCD/crops/2mm/CINGULATE./mask/Lcrops
crop_file_suffix: _cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/CCD/crops/2mm/CINGULATE./mask/Llabels
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/CCD/train_val_subject.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/CCD/ccd_labels.csv
subject_column_name: 'Subject'
input_size: (1, 18, 41, 38)