# @package dataset.SC-sylv_left_hcp_isomap
dataset_name: SC-sylv_left_hcp_isomap
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/S.C.-sylv./mask/Lskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/S.C.-sylv./mask/Lskeleton_subject.csv
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/S.C.-sylv./mask/Llabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/S.C.-sylv./mask/Llabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/hcp/crops/2mm/S.C.-sylv./mask/Lcrops
crop_file_suffix: _cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/S.C.-sylv./mask/Llabels
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/hcp_isomap_subjects.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/hcp_isomap_labels.csv
subject_column_name: 'Subject'
input_size: (1, 38, 36, 49)