# @package dataset.FCLp-subsc-FCLa-INSULA_right
dataset_name: FCLp-subsc-FCLa-INSULA_right
pickle_normal: ${dataset_folder}/cnp/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/cnp/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/cnp/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/cnp/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Rcrops
foldlabel_dir: ${dataset_folder}/cnp/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Rlabels
foldlabel_all: ${dataset_folder}/cnp/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/cnp/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/cnp/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Rdistbottom
distbottom_all: ${dataset_folder}/cnp/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Rdistbottom.npy
subjects_distbottom_all: ${dataset_folder}/cnp/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/cnp/subjects_full.csv
subject_labels_file: ${dataset_folder}/cnp/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 37, 44, 51)