# @package dataset.SFmedian-SFpoltr-SFsup_left
dataset_name: SFmedian-SFpoltr-SFsup_left
pickle_normal: ${dataset_folder}/cnp/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/cnp/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/cnp/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/cnp/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Lcrops
foldlabel_dir: ${dataset_folder}/cnp/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Llabels
foldlabel_all: ${dataset_folder}/cnp/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/cnp/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/cnp/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Ldistbottom
distbottom_all: ${dataset_folder}/cnp/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/cnp/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/cnp/subjects_full.csv
subject_labels_file: ${dataset_folder}/cnp/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 31, 54, 58)