# @package dataset.FCMpost-SpC_left
dataset_name: FCMpost-SpC_left
pickle_normal: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/F.C.M.post.-S.p.C./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/F.C.M.post.-S.p.C./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/F.C.M.post.-S.p.C./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/F.C.M.post.-S.p.C./mask/Lcrops
foldlabel_dir: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/F.C.M.post.-S.p.C./mask/Llabels
foldlabel_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/F.C.M.post.-S.p.C./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/F.C.M.post.-S.p.C./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/F.C.M.post.-S.p.C./mask/Ldistbottom
distbottom_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/F.C.M.post.-S.p.C./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/F.C.M.post.-S.p.C./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/schizconnect-vip-prague/subjects_full.csv
subject_labels_file: ${dataset_folder}/schizconnect-vip-prague/participants.csv
subject_column_name: 'Subject'
input_size: (1, 16, 45, 31)