# @package dataset.SFinter-SFsup_right
dataset_name: SFinter-SFsup_right
pickle_normal: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.inter.-S.F.sup./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.inter.-S.F.sup./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.inter.-S.F.sup./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.inter.-S.F.sup./mask/Rcrops
foldlabel_dir: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.inter.-S.F.sup./mask/Rlabels
foldlabel_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.inter.-S.F.sup./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.inter.-S.F.sup./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.inter.-S.F.sup./mask/Rdistbottom
distbottom_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.inter.-S.F.sup./mask/Rdistbottom.npy
subjects_distbottom_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.inter.-S.F.sup./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/schizconnect-vip-prague/subjects_full.csv
subject_labels_file: ${dataset_folder}/schizconnect-vip-prague/participants.csv
subject_column_name: 'Subject'
input_size: (1, 31, 50, 53)