# @package dataset.SFint-FCMant_left
dataset_name: SFint-FCMant_left
pickle_normal: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.int.-F.C.M.ant./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.int.-F.C.M.ant./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.int.-F.C.M.ant./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.int.-F.C.M.ant./mask/Lcrops
foldlabel_dir: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.int.-F.C.M.ant./mask/Llabels
foldlabel_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.int.-F.C.M.ant./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.int.-F.C.M.ant./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.int.-F.C.M.ant./mask/Ldistbottom
distbottom_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.int.-F.C.M.ant./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.F.int.-F.C.M.ant./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/schizconnect-vip-prague/subjects_full.csv
subject_labels_file: ${dataset_folder}/schizconnect-vip-prague/participants.csv
subject_column_name: 'Subject'
input_size: (1, 16, 55, 52)