# @package dataset.STs-SGSM_left
dataset_name: STs-SGSM_left
pickle_normal: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.T.s.-S.GSM./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.T.s.-S.GSM./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.T.s.-S.GSM./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.T.s.-S.GSM./mask/Lcrops
foldlabel_dir: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.T.s.-S.GSM./mask/Llabels
foldlabel_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.T.s.-S.GSM./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.T.s.-S.GSM./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.T.s.-S.GSM./mask/Ldistbottom
distbottom_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.T.s.-S.GSM./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/schizconnect-vip-prague/crops/2mm/S.T.s.-S.GSM./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/schizconnect-vip-prague/subjects_full.csv
subject_labels_file: ${dataset_folder}/schizconnect-vip-prague/participants.csv
subject_column_name: 'Subject'
input_size: (1, 25, 55, 56)