# @package _global_
dataset_folder: /lustre/fswork/projects/rech/tgu/umy22uu/Runs/70_self-supervised_two-regions/Input
save_dir: /lustre/fswork/projects/rech/tgu/umy22uu/Runs/70_self-supervised_two-regions/Output