# @package _global_
test: False
mode: encoder
contrastive_model: BarlowTwins
BT_correlation: 'cross'
with_labels: False
proportion_pure_contrastive: 1.0
temperature_initial: 0.1
temperature: 0.1
temperature_supervised: 0.3
lambda_BT: 0.01