# @package dataset.FCLp-SGSM_left
dataset_name: FCLp-SGSM_left
pickle_normal: ${dataset_folder}/hcp/crops/2mm/F.C.L.p.-S.GSM./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/hcp/crops/2mm/F.C.L.p.-S.GSM./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/hcp/crops/2mm/F.C.L.p.-S.GSM./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/hcp/crops/2mm/F.C.L.p.-S.GSM./mask/Lcrops
foldlabel_dir: ${dataset_folder}/hcp/crops/2mm/F.C.L.p.-S.GSM./mask/Llabels
foldlabel_all: ${dataset_folder}/hcp/crops/2mm/F.C.L.p.-S.GSM./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/hcp/crops/2mm/F.C.L.p.-S.GSM./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/hcp/crops/2mm/F.C.L.p.-S.GSM./mask/Ldistbottom
distbottom_all: ${dataset_folder}/hcp/crops/2mm/F.C.L.p.-S.GSM./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/hcp/crops/2mm/F.C.L.p.-S.GSM./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/hcp/FIP/fake_train_val.csv
test_csv_file: ${dataset_folder}/hcp/Handedness/union_splits.csv
# splits_basedir: /neurospin/dico/data/deep_folding/current/datasets/hcp/FIP/split_
subject_labels_file: ${dataset_folder}/hcp/Handedness/handedness_labels.csv
subject_column_name: 'Subject'
input_size: (1, 26, 50, 44)