# @package dataset.FIP_right
dataset_name: FIP_right
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/F.I.P./mask/Rskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/F.I.P./mask/Rskeleton_subject.csv
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/F.I.P./mask/Rlabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/F.I.P./mask/Rlabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/hcp/crops/2mm/F.I.P./mask/Rcrops
crop_file_suffix: _cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/F.I.P./mask/Rlabels
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/FIP/fake_train_val.csv
test_csv_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/FIP/union_splits.csv
# splits_basedir: /neurospin/dico/data/deep_folding/current/datasets/hcp/FIP/split_
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/FIP/FIP_labels.csv
subject_column_name: 'Subject'
input_size: (1, 39, 45, 44)