# @package dataset.FPO-SCu-ScCal_right
dataset_name: FPO-SCu-ScCal_right
pickle_normal: ${dataset_folder}/UkBioBank40/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Rcrops
foldlabel_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Rlabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank40/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Rdistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Rdistbottom.npy
subjects_distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/F.P.O.-S.Cu.-Sc.Cal./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/UkBioBank40/42433_subjects.csv
subject_labels_file: ${dataset_folder}/UkBioBank/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 26, 42, 55)