# @package dataset.ORBITAL_left
dataset_name: ORBITAL_left
pickle_normal: ${dataset_folder}/UkBioBank40/crops/2mm/ORBITAL/mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/ORBITAL/mask/Lskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank40/crops/2mm/ORBITAL/mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank40/crops/2mm/ORBITAL/mask/Lcrops
foldlabel_dir: ${dataset_folder}/UkBioBank40/crops/2mm/ORBITAL/mask/Llabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/ORBITAL/mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/ORBITAL/mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank40/crops/2mm/ORBITAL/mask/Ldistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/ORBITAL/mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/ORBITAL/mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/UkBioBank40/21425_new_subjects.csv
subject_labels_file: ${dataset_folder}/UkBioBank/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 30, 38, 22)