# @package dataset.SFmedian-SFpoltr-SFsup_right
dataset_name: SFmedian-SFpoltr-SFsup_right
pickle_normal: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Rcrops
foldlabel_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Rlabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Rdistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Rdistbottom.npy
subjects_distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/UkBioBank40/42433_subjects.csv
subject_labels_file: ${dataset_folder}/UkBioBank/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 30, 52, 55)