# @package dataset.STs_left
dataset_name: STs_left
pickle_normal: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.s./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.s./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.s./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.s./mask/Lcrops
foldlabel_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.s./mask/Llabels
foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.s./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.s./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.s./mask/Ldistbottom
distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.s./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/UkBioBank40/crops/2mm/S.T.s./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/UkBioBank40/42433_subjects.csv
subject_labels_file: ${dataset_folder}/UkBioBank/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 25, 55, 50)