# @package dataset.FCMpost-SpC_right
dataset_name: FCMpost-SpC_right
pickle_normal: ${dataset_folder}/synesthetes/crops/2mm/F.C.M.post.-S.p.C./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/synesthetes/crops/2mm/F.C.M.post.-S.p.C./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/synesthetes/crops/2mm/F.C.M.post.-S.p.C./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/synesthetes/crops/2mm/F.C.M.post.-S.p.C./mask/Rcrops
foldlabel_dir: ${dataset_folder}/synesthetes/crops/2mm/F.C.M.post.-S.p.C./mask/Rlabels
foldlabel_all: ${dataset_folder}/synesthetes/crops/2mm/F.C.M.post.-S.p.C./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/synesthetes/crops/2mm/F.C.M.post.-S.p.C./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/synesthetes/crops/2mm/F.C.M.post.-S.p.C./mask/Rdistbottom
distbottom_all: ${dataset_folder}/synesthetes/crops/2mm/F.C.M.post.-S.p.C./mask/Rdistbottom.npy
subjects_distbottom_all: ${dataset_folder}/synesthetes/crops/2mm/F.C.M.post.-S.p.C./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/synesthetes/subjects_full.csv
subject_labels_file: ${dataset_folder}/synesthetes/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 17, 47, 31)