# @package dataset.STsbr_right
dataset_name: STsbr_right
pickle_normal: ${dataset_folder}/synesthetes/crops/2mm/S.T.s.br./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/synesthetes/crops/2mm/S.T.s.br./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/synesthetes/crops/2mm/S.T.s.br./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/synesthetes/crops/2mm/S.T.s.br./mask/Rcrops
foldlabel_dir: ${dataset_folder}/synesthetes/crops/2mm/S.T.s.br./mask/Rlabels
foldlabel_all: ${dataset_folder}/synesthetes/crops/2mm/S.T.s.br./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/synesthetes/crops/2mm/S.T.s.br./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/synesthetes/crops/2mm/S.T.s.br./mask/Rdistbottom
distbottom_all: ${dataset_folder}/synesthetes/crops/2mm/S.T.s.br./mask/Rdistbottom.npy
subjects_distbottom_all: ${dataset_folder}/synesthetes/crops/2mm/S.T.s.br./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/synesthetes/subjects_full.csv
subject_labels_file: ${dataset_folder}/synesthetes/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 28, 38, 42)