# @package dataset.CINGULATE_left
dataset_name: CINGULATE_left
pickle_normal: ${dataset_folder}/biobd/crops/2mm/CINGULATE./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/biobd/crops/2mm/CINGULATE./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/biobd/crops/2mm/CINGULATE./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/biobd/crops/2mm/CINGULATE./mask/Lcrops
foldlabel_dir: ${dataset_folder}/biobd/crops/2mm/CINGULATE./mask/Llabels
foldlabel_all: ${dataset_folder}/biobd/crops/2mm/CINGULATE./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/biobd/crops/2mm/CINGULATE./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/biobd/crops/2mm/CINGULATE./mask/Ldistbottom
distbottom_all: ${dataset_folder}/biobd/crops/2mm/CINGULATE./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/biobd/crops/2mm/CINGULATE./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/biobd/subjects_full.csv
subject_labels_file: ${dataset_folder}/biobd/participants.csv
subject_column_name: 'Subject'
input_size: (1, 18, 41, 38)