# @package dataset.SFint-FCMant_right
dataset_name: SFint-FCMant_right
pickle_normal: ${dataset_folder}/abide2/crops/2mm/S.F.int.-F.C.M.ant./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/abide2/crops/2mm/S.F.int.-F.C.M.ant./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/abide2/crops/2mm/S.F.int.-F.C.M.ant./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/abide2/crops/2mm/S.F.int.-F.C.M.ant./mask/Rcrops
foldlabel_dir: ${dataset_folder}/abide2/crops/2mm/S.F.int.-F.C.M.ant./mask/Rlabels
foldlabel_all: ${dataset_folder}/abide2/crops/2mm/S.F.int.-F.C.M.ant./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/abide2/crops/2mm/S.F.int.-F.C.M.ant./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/abide2/crops/2mm/S.F.int.-F.C.M.ant./mask/Rdistbottom
distbottom_all: ${dataset_folder}/abide2/crops/2mm/S.F.int.-F.C.M.ant./mask/Rdistbottom.npy
subjects_distbottom_all: ${dataset_folder}/abide2/crops/2mm/S.F.int.-F.C.M.ant./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/abide2/subjects_full.csv
subject_labels_file: ${dataset_folder}/abide2/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 17, 57, 54)