# @package dataset.SOr_left
dataset_name: SOr_left
pickle_normal: ${dataset_folder}/abide2/crops/2mm/S.Or./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/abide2/crops/2mm/S.Or./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/abide2/crops/2mm/S.Or./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/abide2/crops/2mm/S.Or./mask/Lcrops
foldlabel_dir: ${dataset_folder}/abide2/crops/2mm/S.Or./mask/Llabels
foldlabel_all: ${dataset_folder}/abide2/crops/2mm/S.Or./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/abide2/crops/2mm/S.Or./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/abide2/crops/2mm/S.Or./mask/Ldistbottom
distbottom_all: ${dataset_folder}/abide2/crops/2mm/S.Or./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/abide2/crops/2mm/S.Or./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/abide2/subjects_full.csv
subject_labels_file: ${dataset_folder}/abide2/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 30, 38, 22)