# @package _global_
apply_augmentations: True
uniform_trim: False
binary_trim: True
fill_value: 0
max_distance: 1
max_translation: 1
keep_bottom: True
keep_top: False
percentage: 10
variable_percentage: False
sigma_noise: 0.  # set to positive to allow noise
patch_size: [1, 7, 16, 16]
mixed_list: ['foldabel', 'cutout'] # give list of augmentations. Applies in following order: foldlabel, cutout, trimdepth