defaults:
  - _self_
  - augmentations: random # translation_only
  - backbone: ConvNet
  - classifier: svm
  - dataset_localization: neurospin
  #- dataset/with_reskel_distbottom/2mm/UKB/STs_left
  # - dataset/with_reskel_distbottom/2mm/UKB/SC-sylv_left
  - dataset/with_reskel_distbottom/2mm/UKB/FIP_right
  # - dataset/with_reskel_distbottom/2mm/UKB/SC-sylv_right
  # - dataset/with_reskel_distbottom/2mm/UKB/CINGULATE_right
  # - dataset/with_reskel_distbottom/2mm/UKB/STs-SGSM_left
  # - dataset/with_reskel_distbottom/2mm/UKB/FCLp-SGSM_left
  # - dataset/with_reskel_distbottom/2mm/schiz_extended/ORBITAL_left
  # - dataset/with_reskel_distbottom/2mm/UKB/SC_SPeC_left
  # - dataset/with_reskel_distbottom/2mm/UKB/SC_SPeC_right
  # - dataset/with_reskel_distbottom/2mm/schiz_extended/SC_SPeC_left_female
  # - dataset/with_reskel_distbottom/2mm/schiz_extended/SC_SPeC_right_female
  # - dataset/local_julien/cingulate_UKB_right.yaml
  #- dataset/local_julien/1-5mm/STs_babies_UKB_right_1-5mm
  # - dataset/local_julien/1-5mm/orbital_UKB_left_1-5mm
  #- dataset/local_julien/1-5mm/cingulate_UKB_right_1-5mm.yaml
  #- dataset/local_julien/old/STs_UkBioBank.yaml
  # - dataset/occipital_schiz_L_strat_bis_threshold1
  - embeddings: embeddings
  - hydra: local
  - label: diagnosis
  - mode: encoder
  - model: SimCLR_fusion
  - platform: cuda_not_brainvisa
  - projection_head: relu
  - trainer: default
  - wandb: identity
  - override hydra/job_logging: custom

data: ${oc.dict.values:dataset}
datakey: ${oc.dict.keys:dataset}
