# @package dataset.orbital_left_hcp_supervised
dataset_name: orbital_left_hcp_supervised
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/ORBITAL/mask/Lskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/ORBITAL/mask/Lskeleton_subject.csv
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/ORBITAL/mask/Llabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/ORBITAL/mask/Llabel_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/papers/miccai2023/Input/datasets/hcp/crops/2mm/ORBITAL/mask/Lcrops
crop_file_suffix: _cropped_skeleton.nii.gz
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/ORBITAL/mask/Llabels
distbottom_dir: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/ORBITAL/mask/Ldistbottom
distbottom_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/ORBITAL/mask/Ldistbottom.npy
subjects_distbottom_all: /neurospin/dico/data/deep_folding/current/datasets/hcp/crops/2mm/ORBITAL/mask/Ldistbottom_subject.csv
pickle_benchmark: 
train_csv_file: /neurospin/dico/data/deep_folding/current/datasets/orbital_patterns/Troiani/split_0-6.csv
val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/orbital_patterns/Troiani/split_7.csv
test_csv_file: /neurospin/dico/data/deep_folding/current/datasets/orbital_patterns/Troiani/split_8-9.csv
#splits_basedir: /neurospin/dico/data/deep_folding/current/datasets/hcp/hcp_subjects_train_split_
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/hcp/hcp_OFC_labels_from_0.csv
subject_column_name: 'Subject'
input_size: (1, 30, 38, 22)
