# @package dataset.OCCIPITAL_right
dataset_name: OCCIPITAL_right
pickle_normal: ${dataset_folder}/bsnip1/crops/2mm/OCCIPITAL/mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/bsnip1/crops/2mm/OCCIPITAL/mask/Rskeleton.npy
subjects_all: ${dataset_folder}/bsnip1/crops/2mm/OCCIPITAL/mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/bsnip1/crops/2mm/OCCIPITAL/mask/Rcrops
foldlabel_dir: ${dataset_folder}/bsnip1/crops/2mm/OCCIPITAL/mask/Rlabels
foldlabel_all: ${dataset_folder}/bsnip1/crops/2mm/OCCIPITAL/mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/bsnip1/crops/2mm/OCCIPITAL/mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/bsnip1/crops/2mm/OCCIPITAL/mask/Rdistbottom
distbottom_all: ${dataset_folder}/bsnip1/crops/2mm/OCCIPITAL/mask/Rdistbottom.npy
subjects_distbottom_all: ${dataset_folder}/bsnip1/crops/2mm/OCCIPITAL/mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/bsnip1/subjects_full.csv
subject_labels_file: ${dataset_folder}/bsnip1/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 35, 30, 46)