# @package dataset.FCLp-SGSM_right
dataset_name: FCLp-SGSM_right
pickle_normal: ${dataset_folder}/UkBioBank/crops/2mm/F.C.L.p.-S.GSM./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank/crops/2mm/F.C.L.p.-S.GSM./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank/crops/2mm/F.C.L.p.-S.GSM./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank/crops/2mm/F.C.L.p.-S.GSM./mask/Rcrops
foldlabel_dir: ${dataset_folder}/UkBioBank/crops/2mm/F.C.L.p.-S.GSM./mask/Rlabels
foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/F.C.L.p.-S.GSM./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/F.C.L.p.-S.GSM./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank/crops/2mm/F.C.L.p.-S.GSM./mask/Rdistbottom
distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/F.C.L.p.-S.GSM./mask/Rdistbottom.npy
subjects_distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/F.C.L.p.-S.GSM./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/UkBioBank/subjects_full.csv
subject_labels_file: ${dataset_folder}/UkBioBank/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 27, 45, 43)