# @package dataset.SC_SPeC_left.yaml
dataset_name: SC_SPeC_left
pickle_normal: ${dataset_folder}/UkBioBank/crops/2mm/S.C.-S.Pe.C./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank/crops/2mm/S.C.-S.Pe.C./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank/crops/2mm/S.C.-S.Pe.C./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.C.-S.Pe.C./mask/Lcrops
foldlabel_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.C.-S.Pe.C./mask/Llabels
foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/S.C.-S.Pe.C./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/S.C.-S.Pe.C./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.C.-S.Pe.C./mask/Ldistbottom
distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/S.C.-S.Pe.C./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/S.C.-S.Pe.C./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark:
train_val_csv_file: ${dataset_folder}/UkBioBank/subjects_full.csv
subject_labels_file: ${dataset_folder}/UkBioBank/participants_labels.csv
subject_column_name: 'Subject'
input_size: (1, 38, 49, 52)

