# @package dataset.ScCal-SLi
dataset_name: ScCal-SLi
pickle_normal: ${dataset_folder}/UkBioBank/crops/2mm/Sc.Cal.-S.Li./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank/crops/2mm/Sc.Cal.-S.Li./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank/crops/2mm/Sc.Cal.-S.Li./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank/crops/2mm/Sc.Cal.-S.Li./mask/Rcrops
foldlabel_dir: ${dataset_folder}/UkBioBank/crops/2mm/Sc.Cal.-S.Li./mask/Rlabels
foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/Sc.Cal.-S.Li./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/Sc.Cal.-S.Li./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank/crops/2mm/Sc.Cal.-S.Li./mask/Rdistbottom
distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/Sc.Cal.-S.Li./mask/Rdistbottom.npy
subjects_distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/Sc.Cal.-S.Li./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/UkBioBank/subjects_full.csv
subject_labels_file: ${dataset_folder}/UkBioBank/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 26, 42, 44)