# @package dataset.SC-sylv_left_UKB
dataset_name: SC-sylv_left_UKB
pickle_normal: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.C.-sylv./mask/Lskeleton.pkl
numpy_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.C.-sylv./mask/Lskeleton.npy
subjects_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.C.-sylv./mask/Lskeleton_subject.csv
crop_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.C.-sylv./mask/Lcrops
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.C.-sylv./mask/Llabels
foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.C.-sylv./mask/Llabel.npy
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.C.-sylv./mask/Llabel_subject.csv
distbottom_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.C.-sylv./mask/Ldistbottom
distbottom_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.C.-sylv./mask/Ldistbottom.npy
subjects_distbottom_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.C.-sylv./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark:
train_val_csv_file: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/subjects_full.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/participants_labels.csv
subject_column_name: 'Subject'
input_size: (1, 38, 36, 49)


