# @package dataset.SFinf-BROCA-SPeCinf_left
dataset_name: SFinf-BROCA-SPeCinf_left
pickle_normal: ${dataset_folder}/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Lcrops
foldlabel_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Llabels
foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Ldistbottom
distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/UkBioBank/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/UkBioBank/subjects_full.csv
subject_labels_file: ${dataset_folder}/UkBioBank/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 25, 41, 44)