# @package dataset.CINGULATE_right_UKB_sparse_load
dataset_name: CINGULATE_right_UKB_sparse_load
pickle_normal: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/CINGULATE./mask/Rskeleton.pkl
coords_all: /volatile/jl277509/data/UkBioBank/crops/2mm/CINGULATE./mask/Rskeleton_sparse/coords
numpy_all: /volatile/jl277509/data/UkBioBank/crops/2mm/CINGULATE./mask/Rskeleton_sparse/skeleton
subjects_all: /volatile/jl277509/data/UkBioBank/R_subjects_header.csv
crop_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/CINGULATE./mask/Rcrops
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/CINGULATE./mask/Rlabels
foldlabel_all: /volatile/jl277509/data/UkBioBank/crops/2mm/CINGULATE./mask/Rskeleton_sparse/foldlabel
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/CINGULATE./mask/Rlabel_subject.csv
distbottom_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/CINGULATE./mask/Rdistbottom
distbottom_all: /volatile/jl277509/data/UkBioBank/crops/2mm/CINGULATE./mask/Rskeleton_sparse/distbottom
subjects_distbottom_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/CINGULATE./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark:
train_val_csv_file: /volatile/jl277509/data/UkBioBank/R_subjects.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/participants_labels.csv
subject_column_name: 'Subject'
input_size: (1, 16, 37, 37)
#input_size: (1, 17, 40, 38) #without reskel