# @package dataset.STs_right_UKB_sparse_load
dataset_name: STs_right_UKB_sparse_load
pickle_normal: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.T.s./mask/Rskeleton.pkl
coords_all: /volatile/jl277509/data/UkBioBank/crops/2mm/S.T.s./mask/Rskeleton_sparse/coords
numpy_all: /volatile/jl277509/data/UkBioBank/crops/2mm/S.T.s./mask/Rskeleton_sparse/skeleton
subjects_all: /volatile/jl277509/data/UkBioBank/R_subjects_header.csv
crop_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.T.s./mask/Rcrops
foldlabel_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.T.s./mask/Rlabels
foldlabel_all: /volatile/jl277509/data/UkBioBank/crops/2mm/S.T.s./mask/Rskeleton_sparse/foldlabel
subjects_foldlabel_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.T.s./mask/Rlabel_subject.csv
distbottom_dir: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.T.s./mask/Rdistbottom
distbottom_all: /volatile/jl277509/data/UkBioBank/crops/2mm/S.T.s./mask/Rskeleton_sparse/distbottom
subjects_distbottom_all: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.T.s./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: null
train_val_csv_file: /volatile/jl277509/data/UkBioBank/R_subjects.csv
subject_labels_file: /neurospin/dico/data/deep_folding/current/datasets/UkBioBank/participants.csv
subject_column_name: participant_id
input_size: (1, 24, 52, 51)
