# @package dataset.fronto-parietal_medial_face_right
dataset_name: fronto-parietal_medial_face_right
pickle_normal: ${dataset_folder}/abide1/crops/2mm/fronto-parietal_medial_face./mask/Rskeleton.pkl
numpy_all: ${dataset_folder}/abide1/crops/2mm/fronto-parietal_medial_face./mask/Rskeleton.npy
subjects_all: ${dataset_folder}/abide1/crops/2mm/fronto-parietal_medial_face./mask/Rskeleton_subject.csv
crop_dir: ${dataset_folder}/abide1/crops/2mm/fronto-parietal_medial_face./mask/Rcrops
foldlabel_dir: ${dataset_folder}/abide1/crops/2mm/fronto-parietal_medial_face./mask/Rlabels
foldlabel_all: ${dataset_folder}/abide1/crops/2mm/fronto-parietal_medial_face./mask/Rlabel.npy
subjects_foldlabel_all: ${dataset_folder}/abide1/crops/2mm/fronto-parietal_medial_face./mask/Rlabel_subject.csv
distbottom_dir: ${dataset_folder}/abide1/crops/2mm/fronto-parietal_medial_face./mask/Rdistbottom
distbottom_all: ${dataset_folder}/abide1/crops/2mm/fronto-parietal_medial_face./mask/Rdistbottom.npy
subjects_distbottom_all: ${dataset_folder}/abide1/crops/2mm/fronto-parietal_medial_face./mask/Rdistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/abide1/subjects_full.csv
subject_labels_file: ${dataset_folder}/abide1/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 24, 82, 58)