# @package dataset.SFint-SR_left
dataset_name: SFint-SR_left
pickle_normal: ${dataset_folder}/abide1/crops/2mm/S.F.int.-S.R./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/abide1/crops/2mm/S.F.int.-S.R./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/abide1/crops/2mm/S.F.int.-S.R./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/abide1/crops/2mm/S.F.int.-S.R./mask/Lcrops
foldlabel_dir: ${dataset_folder}/abide1/crops/2mm/S.F.int.-S.R./mask/Llabels
foldlabel_all: ${dataset_folder}/abide1/crops/2mm/S.F.int.-S.R./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/abide1/crops/2mm/S.F.int.-S.R./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/abide1/crops/2mm/S.F.int.-S.R./mask/Ldistbottom
distbottom_all: ${dataset_folder}/abide1/crops/2mm/S.F.int.-S.R./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/abide1/crops/2mm/S.F.int.-S.R./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/abide1/subjects_full.csv
subject_labels_file: ${dataset_folder}/abide1/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 16, 55, 58)