# @package dataset.STi-SOTlat_left
dataset_name: STi-SOTlat_left
pickle_normal: ${dataset_folder}/abide1/crops/2mm/S.T.i.-S.O.T.lat./mask/Lskeleton.pkl
numpy_all: ${dataset_folder}/abide1/crops/2mm/S.T.i.-S.O.T.lat./mask/Lskeleton.npy
subjects_all: ${dataset_folder}/abide1/crops/2mm/S.T.i.-S.O.T.lat./mask/Lskeleton_subject.csv
crop_dir: ${dataset_folder}/abide1/crops/2mm/S.T.i.-S.O.T.lat./mask/Lcrops
foldlabel_dir: ${dataset_folder}/abide1/crops/2mm/S.T.i.-S.O.T.lat./mask/Llabels
foldlabel_all: ${dataset_folder}/abide1/crops/2mm/S.T.i.-S.O.T.lat./mask/Llabel.npy
subjects_foldlabel_all: ${dataset_folder}/abide1/crops/2mm/S.T.i.-S.O.T.lat./mask/Llabel_subject.csv
distbottom_dir: ${dataset_folder}/abide1/crops/2mm/S.T.i.-S.O.T.lat./mask/Ldistbottom
distbottom_all: ${dataset_folder}/abide1/crops/2mm/S.T.i.-S.O.T.lat./mask/Ldistbottom.npy
subjects_distbottom_all: ${dataset_folder}/abide1/crops/2mm/S.T.i.-S.O.T.lat./mask/Ldistbottom_subject.csv
crop_file_suffix: _cropped_skeleton.nii.gz
pickle_benchmark: 
train_val_csv_file: ${dataset_folder}/abide1/subjects_full.csv
subject_labels_file: ${dataset_folder}/abide1/participants.csv
subject_column_name: 'participant_id'
input_size: (1, 34, 64, 53)